### ISSUE TITLE
Chrome check_audit_requirements Fails on Mac

### ISSUE THREAD

**Issue by rsh52** [Novartis/shinyValidator#25]
The `check_audit_requirements()` function stops any use of `audit_app()` on a boilerplate `golem` application for the below session information:

```
sessionInfo()
R version 4.2.0 (2022-04-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7
```

I found after forking the repo and removing this check that the `audit_app` ran as expected. I believe the issue is something to do with the use of `system("which google-chrome")` under `check_audit_requirements`. 

`chromote::find_chrome()` works fine though I'm not sure if it fulfills all the criteria needed here. If all that's needed is an accurate return that chrome installation exists, this could be an option.

(@DivadNojnarg I was the one asking questions about this in the R/Pharma workshop yesterday 😅 )

**Comment by DivadNojnarg** [comment]
Hi Rich,

Thanks for getting back here. I am gonna use `find_chrome` from `{chromote}` and apply the same code in the package to detect chrome.  I added RStudio/Posit as copyright holder for that function.
